### PR TITLE
Added New Font.

### PR DESCRIPTION
**Pull request by martin-code1**
Creating a font Used Software "FontLab 8". And it is a most Is Used A Making Font.
Why Is A "CKP-Text"? The Geometric Sans Serif Is a design that used in company or channel.

### CODE REVIEW

**Comment by simoncozens** [comment]
Thanks, but the repository template is the wrong place for this.

**Comment by martin-code1** [comment]
@simoncozens ok. but how to make the correct template?

**Comment by simoncozens** [comment]
You don't need to make a new template; press the green "Use this template" button at the top right of https://github.com/googlefonts/googlefonts-project-template to make your own repository using this template to put your font sources in.

**Comment by martin-code1** [comment]
Ok. Great! Thanks. But I cant build the font. @simoncozens

**Comment by martin-code1** [comment]
How I Made error of "Build and test". How to fix?! @simoncozens

**Comment by simoncozens** [comment]
What's the error?

**Pull request closed without merging**
