### PR TITLE
copied in the GF Latin .plist file which contains GF African, Beyond, Vietnamese, etc

### PR DESCRIPTION
**Pull request by agyeiarcher**
Imported from https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/glyphs

### CODE REVIEW

**Comment by simoncozens** [comment]
I'm not against this and it looks good, but perhaps we need to add a note to the user in the README about what they need to do with it. At least, *I* don't know what users need to do with it; would they need to copy it into their `~/Application Support/Glyphs 3` directory somewhere, or does it just work as-is? Even if it just works as-is, a little explanation about how to spin up a new African/Vietnamese/Beyond/etc. font would be nice.

**Comment by eliheuer** [comment]
I like that this makes things easy for people starting new projects!

My only concern is that the upstream glyphsets get updated and these get out of date.

**Comment by eliheuer** [comment]
I just pushed an update to this PR, it:
- Removes the old plist file
- Updates the readme with a modified version of PR #108

**Comment by simoncozens** [comment]
I added a script we can run to update it (probably from CI). LGTM.

**Pull request merged**
