### PR TITLE
Added GF Latin Core

### LINKED ISSUE #83: Add .plist for GF glyphsets in /sources
So designers using the template repo can see the bare minimum expected

### PR DESCRIPTION
**Pull request by RosaWagner**
- as a filter list
- 3 missing glyphs in sources

fixes #83

### CODE REVIEW

**Comment by eliheuer** [comment]
Did you see #82? This seems like it might fix that as well.

**Comment by eliheuer** [comment]
Also, It would be helpful to include an explanation of what the [custom filter list](https://github.com/googlefonts/googlefonts-project-template/pull/84/commits/73ceb57766e7c5a7bb0c3c34011625304d44b327) is and why it is needed in a README in the source directory, or possible the main README.

**Comment by razvanm** [comment]
> Also, It would be helpful to include an explanation of what the [custom filter list](https://github.com/googlefonts/googlefonts-project-template/pull/84/commits/73ceb57766e7c5a7bb0c3c34011625304d44b327) is and why it is needed in a README in the source directory, or possibly the main README.

Was the purpose of the `CustomFilter_GFLatinCore.plist` explained somewhere? I'm trying to add a font following this template and I'm confused if I should delete this file or make some changes to it.

**Comment by RosaWagner** [comment]
if you use GlyphsApp, the plist will give you a filter list of glyphs to support Google Fonts Latin Core glyphset.

**Comment by razvanm** [comment]
I had no idea that it was related to the Glyphs App. Thanks for the explanation! As @eliheuer also suggested above, indicating this in a README in that directory (or the main README) would be helpful to avoid confusion.

**Pull request merged**
